### ISSUE TITLE
Support for PocketCast Files

### ISSUE THREAD

**Issue by benjaminyam** [nwithan8/pycketcasts#3]
Hello, would appreciate if you could consider adding this feature.

I would love to automate uploading of files to PocketCast account.

![image](https://user-images.githubusercontent.com/9518517/104981283-4ad95d80-5a43-11eb-9399-7746862183ab.png)

**Comment by nwithan8** [comment]
Already am.
Going to close this, since it's a duplicate of https://github.com/nwithan8/pycketcasts/issues/2
