### ISSUE TITLE
Homeassistant

### ISSUE THREAD

**Issue by strelniece** [nwithan8/pycketcasts#4]
Hi,

In the docs it says the library is used in homassistant.

How? Where?  Running hass and it seems like your library is just perfect but can't find anything more about it.

**Comment by nwithan8** [comment]
https://github.com/home-assistant/core/pull/44008

**Comment by strelniece** [comment]
Ah, but only "unlistened episodes"? or do you have plans to implement more features from your library?

**Comment by nwithan8** [comment]
I built the new library just to replace an old dependency in Home Assistant. I don't have any plans to add new features to the Home Assistant plugin. Feel free to make your own PR for Home Assistant

**Comment by strelniece** [comment]
It might be that this is what takes me to sit down and learn python proberly...
